openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/locations:
    get:
      summary: 'Show all locations.'
      operationId: showAllLocations
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a new location.'
      operationId: storeANewLocation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                '{':
                  type: "'name':"
                  description: "'Bar do Zeca',\n     'X': 25,\n     'Y': 50,\n     'opensAt': 17:00,\n     'closesAt': 00:00\n }"
                  example: aut
      security: []
  '/api/locations/{id}':
    get:
      summary: 'Show location by id.'
      operationId: showLocationById
      description: ''
      parameters:
        -
          in: query
          name: id
          description: "location's id"
          example: pariatur
          required: false
          schema:
            type: string
            description: "location's id"
            example: pariatur
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    'id': 1,\n    'name': 'Bar do Zeca',\n    'X': 25,\n    'Y': 50,\n    'opensAt': 17:00,\n    'closesAt': 00:00\n}"
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     'name': 'Bar do Zeca',\n     'X': 25,\n     'Y': 50,\n     'opensAt': 17:00,\n     'closesAt': 00:00\n }"
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                '{':
                  type: "'name':"
                  description: "'Bar do Zeca',\n      'X': 25,\n      'Y': 50,\n      'opensAt': 17:00,\n      'closesAt': 00:00\n  }"
                  example: magnam
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters:
        -
          in: query
          name: id
          description: "location's id"
          example: autem
          required: false
          schema:
            type: string
            description: "location's id"
            example: autem
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the location.'
        example: 9
        required: true
        schema:
          type: integer
  /api/proximity/locations:
    get:
      summary: 'Return locations by proximity'
      operationId: returnLocationsByProximity
      description: ''
      parameters: []
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Algum dos parametros X,Y ou Hour não foi informado'
                properties:
                  error:
                    type: string
                    example: 'Algum dos parametros X,Y ou Hour não foi informado'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
