openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/locations:
    get:
      summary: 'Show all locations.'
      operationId: showAllLocations
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "[{\n      'name': 'Bar do Zeca',\n      'X': 25,\n      'Y': 50,\n      'opensAt': 17:00,\n      'closesAt': 00:00,\n      'publicLocation': 0\n  }] array of locations"
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a new location.'
      operationId: storeANewLocation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Location's name"
                  example: 'Restaurante da Lapa'
                X:
                  type: string
                  description: 'Coordinate X'
                  example: '56'
                'Y':
                  type: string
                  description: 'Coordinate Y'
                  example: '89'
                opensAt:
                  type: string
                  description: 'Opening time of the location'
                  example: '11:00'
                closesAt:
                  type: string
                  description: 'Closing time of the location'
                  example: '21:00'
                publicLocation:
                  type: string
                  description: 'Set 1 for publicLocations, indication the is always open'
                  example: '1'
      security: []
  '/api/locations/{id}':
    get:
      summary: 'Show location by id.'
      operationId: showLocationById
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    'id': 1,\n    'name': 'Bar do Zeca',\n    'X': 25,\n    'Y': 50,\n    'opensAt': 17:00,\n    'closesAt': 00:00,\n    'publicLocation': 0\n}"
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     'name': 'Bar do Zeca',\n     'X': 25,\n     'Y': 50,\n     'opensAt': 17:00,\n     'closesAt': 00:00,\n     'publicLocation': 0\n }"
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Location's name"
                  example: 'Restaurante da Lapa'
                X:
                  type: string
                  description: 'Coordinate X'
                  example: '56'
                'Y':
                  type: string
                  description: 'Coordinate Y'
                  example: '89'
                opensAt:
                  type: string
                  description: 'Opening time of the location'
                  example: '11:00'
                closesAt:
                  type: string
                  description: 'Closing time of the location'
                  example: '21:00'
                publicLocation:
                  type: string
                  description: 'Set 1 for publicLocations, indication the is always open'
                  example: '1'
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: "Optional parameter. location's id"
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 4
  /api/proximity/locations:
    get:
      summary: 'Return locations by proximity'
      operationId: returnLocationsByProximity
      description: ''
      parameters:
        -
          in: query
          name: X
          description: 'coordinate X'
          example: '23'
          required: false
          schema:
            type: string
            description: 'coordinate X'
            example: '23'
        -
          in: query
          name: 'Y'
          description: 'coordinate Y'
          example: '50'
          required: false
          schema:
            type: string
            description: 'coordinate Y'
            example: '50'
        -
          in: query
          name: hour
          description: 'look for open locations at this time'
          example: '12:00'
          required: false
          schema:
            type: string
            description: 'look for open locations at this time'
            example: '12:00'
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n      'name': 'Bar do Zeca',\n      'status': 'open'\n      'opensAt': 17:00,\n      'closesAt': 00:00,\n      'publicLocation': 0\n  }"
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
