openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/locations:
    get:
      summary: 'Show all locations.'
      operationId: showAllLocations
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a new location.'
      operationId: storeANewLocation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oordhfruwai
                '{':
                  type: "'name':"
                  description: "'Bar do Zeca',\n     'X': 25,\n     'Y': 50,\n     'opensAt': 17:00,\n     'closesAt': 00:00\n }"
                  example: ut
              required:
                - name
      security: []
  '/api/locations/{id}':
    get:
      summary: 'Show location by id.'
      operationId: showLocationById
      description: ''
      parameters:
        -
          in: query
          name: id
          description: "location's id"
          example: et
          required: false
          schema:
            type: string
            description: "location's id"
            example: et
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    'id': 1,\n    'name': 'Bar do Zeca',\n    'X': 25,\n    'Y': 50,\n    'opensAt': 17:00,\n    'closesAt': 00:00\n}"
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the location.'
        example: 9
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
